lecteurcarte.o: lecteurcarte.cpp lecteurcarte.h base_clients.h voyants.h \
 timer.h boutons.h prise.h generateursave.h
borne.o: borne.cpp lecteurcarte.h
base_clients.o: base_clients.cpp base_clients.h
voyants.o: voyants.cpp voyants.h timer.h
timer.o: timer.cpp timer.h
boutons.o: boutons.cpp boutons.h
prise.o: prise.cpp prise.h
generateursave.o: generateursave.cpp generateursave.h prise.h voyants.h \
 boutons.h lecteurcarte.h
